---
- name: Creates directory
  file:
    path: ~/backend
    state: directory
    mode: 0755

- name: Unarchive artifact
  unarchive:
    remote_src: yes
    src: ../../artifact.tar.gz
    dest: ~/backend/artifact.tar.gz

- name: Copy env file
  shell: cp /tmp/.env /home/ubuntu/project

- name: Start app
  shell: |
    cd ~/backend
    npm install
    npm i -g pm2
    npm run build
    pm2 stop default
    pm2 start npm -- start --wait-ready